language: python

python:
  - 2.7

services: postgresql

env:
  - DJANGO=1.7.4

before_install:
  - export DJANGO_SETTINGS_MODULE=game_website.settings
  - export PYTHONPATH=$HOME/builds/jsamara/game-website

install:
  - pip install -r requirements.txt
  - pip install django==$DJANGO --quiet
  - pip install psycopg2 --quiet

before_script:
  - psql -c "CREATE DATABASE travisdb;" -U postgres
  - DJANGO_ENV='travis' python manage.py migrate

script:
  - DJANGO_ENV='travis' python manage.py test
