language: python

python:
  - 2.7

services: postgresql

env:
  - DJANGO=1.7.4

before_install:
  - export DJANGO_SETTINGS_MODULE=game_website.settings

install:
  - pip install -r requirements.txt
  - pip install django==$DJANGO --quiet
  - pip install psycopg2 --quiet
  - pip install coveralls

before_script:
  - psql -c "CREATE DATABASE travisdb;" -U postgres
  - DJANGO_ENV='travis' python manage.py migrate

script:
  - DJANGO_ENV='travis' coverage run --source='core' manage.py test

after_success:
  - coveralls
